/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TAuthorRecord extends org.jooq.impl.UpdatableRecordImpl<org.javaclub.opensource.demos.jooq.tables.records.TAuthorRecord> {

	private static final long serialVersionUID = -1038600218;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> fetchTBookList() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK)
			.where(org.javaclub.opensource.demos.jooq.tables.TBook.AUTHOR_ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setFirstName(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.FIRST_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getFirstName() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.FIRST_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setLastName(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.LAST_NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getLastName() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.LAST_NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setDateOfBirth(java.sql.Date value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.DATE_OF_BIRTH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Date getDateOfBirth() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.DATE_OF_BIRTH);
	}

	/**
	 * An uncommented item
	 */
	public void setYearOfBirth(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.YEAR_OF_BIRTH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getYearOfBirth() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TAuthor.YEAR_OF_BIRTH);
	}

	/**
	 * Create a detached TAuthorRecord
	 */
	public TAuthorRecord() {
		super(org.javaclub.opensource.demos.jooq.tables.TAuthor.T_AUTHOR);
	}

	/**
	 * Create an attached TAuthorRecord
	 */
	public TAuthorRecord(org.jooq.Configuration configuration) {
		super(org.javaclub.opensource.demos.jooq.tables.TAuthor.T_AUTHOR, configuration);
	}
}
