/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TBookRecord extends org.jooq.impl.UpdatableRecordImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> {

	private static final long serialVersionUID = 1455329873;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBook.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBook.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> fetchTBookToBookStoreList() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE)
			.where(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TBook.ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.author_id]
	 * REFERENCES t_author [test_jooq.t_author.id]
	 * </pre></code>
	 */
	public void setAuthorId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBook.AUTHOR_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.author_id]
	 * REFERENCES t_author [test_jooq.t_author.id]
	 * </pre></code>
	 */
	public java.lang.Integer getAuthorId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBook.AUTHOR_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.author_id]
	 * REFERENCES t_author [test_jooq.t_author.id]
	 * </pre></code>
	 */
	public org.javaclub.opensource.demos.jooq.tables.records.TAuthorRecord fetchTAuthor() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TAuthor.T_AUTHOR)
			.where(org.javaclub.opensource.demos.jooq.tables.TAuthor.ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TBook.AUTHOR_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setTitle(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBook.TITLE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getTitle() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBook.TITLE);
	}

	/**
	 * An uncommented item
	 */
	public void setPublishedIn(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBook.PUBLISHED_IN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getPublishedIn() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBook.PUBLISHED_IN);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.language_id]
	 * REFERENCES t_language [test_jooq.t_language.id]
	 * </pre></code>
	 */
	public void setLanguageId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBook.LANGUAGE_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.language_id]
	 * REFERENCES t_language [test_jooq.t_language.id]
	 * </pre></code>
	 */
	public java.lang.Integer getLanguageId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBook.LANGUAGE_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.language_id]
	 * REFERENCES t_language [test_jooq.t_language.id]
	 * </pre></code>
	 */
	public org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord fetchTLanguage() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TLanguage.T_LANGUAGE)
			.where(org.javaclub.opensource.demos.jooq.tables.TLanguage.ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TBook.LANGUAGE_ID)))
			.fetchOne();
	}

	/**
	 * Create a detached TBookRecord
	 */
	public TBookRecord() {
		super(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK);
	}

	/**
	 * Create an attached TBookRecord
	 */
	public TBookRecord(org.jooq.Configuration configuration) {
		super(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK, configuration);
	}
}
