/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TBookToBookStoreRecord extends org.jooq.impl.UpdatableRecordImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> {

	private static final long serialVersionUID = -803288151;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_store_name]
	 * REFERENCES t_book_store [test_jooq.t_book_store.name]
	 * </pre></code>
	 */
	public void setBookStoreName(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_STORE_NAME, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_store_name]
	 * REFERENCES t_book_store [test_jooq.t_book_store.name]
	 * </pre></code>
	 */
	public java.lang.String getBookStoreName() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_STORE_NAME);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_store_name]
	 * REFERENCES t_book_store [test_jooq.t_book_store.name]
	 * </pre></code>
	 */
	public org.javaclub.opensource.demos.jooq.tables.records.TBookStoreRecord fetchTBookStore() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TBookStore.T_BOOK_STORE)
			.where(org.javaclub.opensource.demos.jooq.tables.TBookStore.NAME.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_STORE_NAME)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_id]
	 * REFERENCES t_book [test_jooq.t_book.id]
	 * </pre></code>
	 */
	public void setBookId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_id]
	 * REFERENCES t_book [test_jooq.t_book.id]
	 * </pre></code>
	 */
	public java.lang.Integer getBookId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_id]
	 * REFERENCES t_book [test_jooq.t_book.id]
	 * </pre></code>
	 */
	public org.javaclub.opensource.demos.jooq.tables.records.TBookRecord fetchTBook() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK)
			.where(org.javaclub.opensource.demos.jooq.tables.TBook.ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 */
	public void setStock(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.STOCK, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getStock() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.STOCK);
	}

	/**
	 * Create a detached TBookToBookStoreRecord
	 */
	public TBookToBookStoreRecord() {
		super(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE);
	}

	/**
	 * Create an attached TBookToBookStoreRecord
	 */
	public TBookToBookStoreRecord(org.jooq.Configuration configuration) {
		super(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE, configuration);
	}
}
