/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TLanguageRecord extends org.jooq.impl.UpdatableRecordImpl<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> {

	private static final long serialVersionUID = 96771452;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> fetchTBookList() throws java.sql.SQLException {
		return create()
			.selectFrom(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK)
			.where(org.javaclub.opensource.demos.jooq.tables.TBook.LANGUAGE_ID.equal(getValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setCd(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.CD, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getCd() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.CD);
	}

	/**
	 * An uncommented item
	 */
	public void setDescription(java.lang.String value) {
		setValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.DESCRIPTION, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getDescription() {
		return getValue(org.javaclub.opensource.demos.jooq.tables.TLanguage.DESCRIPTION);
	}

	/**
	 * Create a detached TLanguageRecord
	 */
	public TLanguageRecord() {
		super(org.javaclub.opensource.demos.jooq.tables.TLanguage.T_LANGUAGE);
	}

	/**
	 * Create an attached TLanguageRecord
	 */
	public TLanguageRecord(org.jooq.Configuration configuration) {
		super(org.javaclub.opensource.demos.jooq.tables.TLanguage.T_LANGUAGE, configuration);
	}
}
