/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the test_jooq schema
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends org.jooq.impl.AbstractKeys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TAuthorRecord> KEY_t_author_PRIMARY = createUniqueKey(org.javaclub.opensource.demos.jooq.tables.TAuthor.T_AUTHOR, org.javaclub.opensource.demos.jooq.tables.TAuthor.ID);
	public static final org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> KEY_t_book_PRIMARY = createUniqueKey(org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK, org.javaclub.opensource.demos.jooq.tables.TBook.ID);
	public static final org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookStoreRecord> KEY_t_book_store_name = createUniqueKey(org.javaclub.opensource.demos.jooq.tables.TBookStore.T_BOOK_STORE, org.javaclub.opensource.demos.jooq.tables.TBookStore.NAME);
	public static final org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> KEY_t_book_to_book_store_PRIMARY = createUniqueKey(org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_STORE_NAME, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID);
	public static final org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> KEY_t_language_PRIMARY = createUniqueKey(org.javaclub.opensource.demos.jooq.tables.TLanguage.T_LANGUAGE, org.javaclub.opensource.demos.jooq.tables.TLanguage.ID);

	// FOREIGN KEY definitions
	public static final org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, org.javaclub.opensource.demos.jooq.tables.records.TAuthorRecord> t_book_ibfk_1 = createForeignKey(KEY_t_author_PRIMARY, org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK, org.javaclub.opensource.demos.jooq.tables.TBook.AUTHOR_ID);
	public static final org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> t_book_ibfk_2 = createForeignKey(KEY_t_language_PRIMARY, org.javaclub.opensource.demos.jooq.tables.TBook.T_BOOK, org.javaclub.opensource.demos.jooq.tables.TBook.LANGUAGE_ID);
	public static final org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, org.javaclub.opensource.demos.jooq.tables.records.TBookStoreRecord> b2bs_book_store_id = createForeignKey(KEY_t_book_store_name, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_STORE_NAME);
	public static final org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> b2bs_book_id = createForeignKey(KEY_t_book_PRIMARY, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.T_BOOK_TO_BOOK_STORE, org.javaclub.opensource.demos.jooq.tables.TBookToBookStore.BOOK_ID);

	/**
	 * No instances
	 */
	private Keys() {}
}
