/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TBookToBookStore extends org.jooq.impl.UpdatableTableImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> {

	private static final long serialVersionUID = 1941929073;

	/**
	 * The singleton instance of t_book_to_book_store
	 */
	public static final org.javaclub.opensource.demos.jooq.tables.TBookToBookStore T_BOOK_TO_BOOK_STORE = new org.javaclub.opensource.demos.jooq.tables.TBookToBookStore();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> __RECORD_TYPE = org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_store_name]
	 * REFERENCES t_book_store [test_jooq.t_book_store.name]
	 * </pre></code>
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.String> BOOK_STORE_NAME = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.String>("book_store_name", org.jooq.impl.SQLDataType.VARCHAR, T_BOOK_TO_BOOK_STORE);

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book_to_book_store.book_id]
	 * REFERENCES t_book [test_jooq.t_book.id]
	 * </pre></code>
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.Integer> BOOK_ID = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.Integer>("book_id", org.jooq.impl.SQLDataType.INTEGER, T_BOOK_TO_BOOK_STORE);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.Integer> STOCK = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, java.lang.Integer>("stock", org.jooq.impl.SQLDataType.INTEGER, T_BOOK_TO_BOOK_STORE);

	/**
	 * No further instances allowed
	 */
	private TBookToBookStore() {
		super("t_book_to_book_store", org.javaclub.opensource.demos.jooq.TestJooq.TEST_JOOQ);
	}

	@Override
	public org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord> getMainKey() {
		return org.javaclub.opensource.demos.jooq.Keys.KEY_t_book_to_book_store_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord>>asList(org.javaclub.opensource.demos.jooq.Keys.KEY_t_book_to_book_store_PRIMARY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookToBookStoreRecord, ?>>asList(org.javaclub.opensource.demos.jooq.Keys.b2bs_book_store_id, org.javaclub.opensource.demos.jooq.Keys.b2bs_book_id);
	}
}
