/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TBook extends org.jooq.impl.UpdatableTableImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> {

	private static final long serialVersionUID = 754431513;

	/**
	 * The singleton instance of t_book
	 */
	public static final org.javaclub.opensource.demos.jooq.tables.TBook T_BOOK = new org.javaclub.opensource.demos.jooq.tables.TBook();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> __RECORD_TYPE = org.javaclub.opensource.demos.jooq.tables.records.TBookRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer> ID = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer>("id", org.jooq.impl.SQLDataType.INTEGER, T_BOOK);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.author_id]
	 * REFERENCES t_author [test_jooq.t_author.id]
	 * </pre></code>
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer> AUTHOR_ID = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer>("author_id", org.jooq.impl.SQLDataType.INTEGER, T_BOOK);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.String> TITLE = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.String>("title", org.jooq.impl.SQLDataType.VARCHAR, T_BOOK);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer> PUBLISHED_IN = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer>("published_in", org.jooq.impl.SQLDataType.INTEGER, T_BOOK);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * FOREIGN KEY [test_jooq.t_book.language_id]
	 * REFERENCES t_language [test_jooq.t_language.id]
	 * </pre></code>
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer> LANGUAGE_ID = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, java.lang.Integer>("language_id", org.jooq.impl.SQLDataType.INTEGER, T_BOOK);

	/**
	 * No further instances allowed
	 */
	private TBook() {
		super("t_book", org.javaclub.opensource.demos.jooq.TestJooq.TEST_JOOQ);
	}

	@Override
	public org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord> getMainKey() {
		return org.javaclub.opensource.demos.jooq.Keys.KEY_t_book_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord>>asList(org.javaclub.opensource.demos.jooq.Keys.KEY_t_book_PRIMARY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.javaclub.opensource.demos.jooq.tables.records.TBookRecord, ?>>asList(org.javaclub.opensource.demos.jooq.Keys.t_book_ibfk_1, org.javaclub.opensource.demos.jooq.Keys.t_book_ibfk_2);
	}
}
