/**
 * This class is generated by jOOQ
 */
package org.javaclub.opensource.demos.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class TLanguage extends org.jooq.impl.UpdatableTableImpl<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> {

	private static final long serialVersionUID = 1051933110;

	/**
	 * The singleton instance of t_language
	 */
	public static final org.javaclub.opensource.demos.jooq.tables.TLanguage T_LANGUAGE = new org.javaclub.opensource.demos.jooq.tables.TLanguage();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> __RECORD_TYPE = org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.Integer> ID = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.Integer>("id", org.jooq.impl.SQLDataType.INTEGER, T_LANGUAGE);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.String> CD = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.String>("cd", org.jooq.impl.SQLDataType.VARCHAR, T_LANGUAGE);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.String> DESCRIPTION = new org.jooq.impl.TableFieldImpl<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord, java.lang.String>("description", org.jooq.impl.SQLDataType.VARCHAR, T_LANGUAGE);

	/**
	 * No further instances allowed
	 */
	private TLanguage() {
		super("t_language", org.javaclub.opensource.demos.jooq.TestJooq.TEST_JOOQ);
	}

	@Override
	public org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord> getMainKey() {
		return org.javaclub.opensource.demos.jooq.Keys.KEY_t_language_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.javaclub.opensource.demos.jooq.tables.records.TLanguageRecord>>asList(org.javaclub.opensource.demos.jooq.Keys.KEY_t_language_PRIMARY);
	}
}
